[package]
name = "administration_portal"
version = "0.1.0"
edition = "2024"
readme = "README.md"
license = "Apache-2.0"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]


[dependencies]
yew = { version="0.21", features=["csr"] }
yew-router = "0.18"
